@password = 22c686ea535d7e238e37f7f97c4e83ba
@password2 = ff6173272bd3567f78e5e50e61349432

### Login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "businessName": "wilson",
  "email": "wilson@gmail.com",
  "password": "{{password2}}"
}

### Login Admin
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "businessName": "Pelaitopaez2",
  "email": "papa2@gmail.com",
  "password": "a3b8616138ad655b3e84b52c371eb951"
}