@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRJZCI6IjY3OGFhNGNhNTQzNDAyOGY2NTViYWVjOCIsImJ1c2luZXNzTmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczNzEzOTQ0NiwiZXhwIjoxNzM3MjI1ODQ2fQ.ENVF00OWd2G4IoFP8OXJzUmumQxRswF_fGBmorkfviM
@url = http://localhost:5000/products

### Create Product
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Product 2",
  "purchasePrice": 10000,
  "marginPercent": 20,
  "sku": "PROD002",
  "stock": 10,
  "category": "678aa9f65434028f655baece",
  "supplier": "678aaa0c5434028f655baed0"
}