@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRJZCI6IjY3OTFjYzlhYmY5MTA1ODZhZGRkYmQ3ZCIsImJ1c2luZXNzTmFtZSI6ImJydW5vIiwiZW1haWwiOiJicnVub0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MzgyOTk4MjIsImV4cCI6MTczODMwMDcyMn0.Ra53C3D47PuIShq3oTiKH-MpF20ZSTkPpf0whGHI5xk
@url = http://localhost:5000/products

### Create Product
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Product 2",
  "purchasePrice": 10000,
  "marginPercent": 20,
  "sku": "PROD002",
  "stock": 10,
  "category": "678aa9f65434028f655baece",
  "supplier": "678aaa0c5434028f655baed0"
}

### Get Products id
GET {{url}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Get Product by id
Get {{url}}/6791cdb935833171ce02f125
Content-Type: application/json
Authorization: Bearer {{jwtToken}}
