@baseUrl = http://localhost:5000
@authUrl = {{baseUrl}}/auth
@tenantsUrl = {{baseUrl}}/tenants
@password = ee981b4c0290790d972477d984fa3388

### 1. Login primero
POST http://localhost:5000/auth/login
Content-Type: application/json
{
    "businessName": "bruno",
    "email": "bruno@gmail.com",
    "password": "ee981b4c0290790d972477d984fa3388"
}

@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRJZCI6IjY3OTFjYzlhYmY5MTA1ODZhZGRkYmQ3ZCIsImJ1c2luZXNzTmFtZSI6ImJydW5vIiwiZW1haWwiOiJicnVub0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MzgxOTE5NTgsImV4cCI6MTczODE5Mjg1OH0.OA7MeDAKGkfD-BPPGKselgItVyjQbx9ishM3XQikiZU

### 2. Actualizar contraseña tenant
PATCH {{tenantsUrl}}/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "newPassword": "asd123"
}

### 3. Crear tenant (opcional)
POST {{tenantsUrl}}
Content-Type: application/json

{ 
    "businessName": "bruno",
    "email": "bruno@gmail.com"
}